### ISSUE TITLE
Installing error in latest build

### ISSUE THREAD

**Issue by cuongpxu** [yzhao062/SUOD#2]
Hi,

I'm facing this error when trying to install suod package through both pip and source. The detail log is below: 

`
ERROR: Command errored out with exit status 1:
     command: /home/alan/anaconda3/envs/cuongpx/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6j6iaixz/suod/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6j6iaixz/suod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ms_fv72w/install-record.txt --single-version-externally-managed --compile --install-headers /home/alan/anaconda3/envs/cuongpx/include/python3.6m/suod
         cwd: /tmp/pip-install-6j6iaixz/suod/
    Complete output (63 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/suod
    copying suod/version.py -> build/lib/suod
    copying suod/__init__.py -> build/lib/suod
    creating build/lib/suod/utils
    copying suod/utils/__init__.py -> build/lib/suod/utils
    copying suod/utils/utility.py -> build/lib/suod/utils
    creating build/lib/suod/models
    copying suod/models/jl_projection.py -> build/lib/suod/models
    copying suod/models/__init__.py -> build/lib/suod/models
    copying suod/models/parallel_processes.py -> build/lib/suod/models
    copying suod/models/cost_predictor.py -> build/lib/suod/models
    copying suod/models/base.py -> build/lib/suod/models
    creating build/lib/suod/models/saved_models
    copying suod/models/saved_models/__init__.py -> build/lib/suod/models/saved_models
    running egg_info
    writing suod.egg-info/PKG-INFO
    writing dependency_links to suod.egg-info/dependency_links.txt
    writing requirements to suod.egg-info/requires.txt
    writing top-level names to suod.egg-info/top_level.txt
    reading manifest file 'suod.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'examples'
    no previously-included directories found matching 'notebooks'
    no previously-included directories found matching 'suod/test'
    warning: no files found matching 'suod/models'
    writing manifest file 'suod.egg-info/SOURCES.txt'
    copying suod/models/saved_models/bps_prediction.joblib -> build/lib/suod/models/saved_models
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6j6iaixz/suod/setup.py", line 52, in <module>
        'Programming Language :: Python :: 3.7',
      File "/home/alan/anaconda3/envs/cuongpx/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/alan/anaconda3/envs/cuongpx/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/alan/anaconda3/envs/cuongpx/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/alan/anaconda3/envs/cuongpx/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/alan/anaconda3/envs/cuongpx/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/alan/anaconda3/envs/cuongpx/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/alan/anaconda3/envs/cuongpx/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/alan/anaconda3/envs/cuongpx/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/alan/anaconda3/envs/cuongpx/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/alan/anaconda3/envs/cuongpx/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/alan/anaconda3/envs/cuongpx/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/alan/anaconda3/envs/cuongpx/lib/python3.6/site-packages/setuptools/command/build_py.py", line 53, in run
        self.build_package_data()
      File "/home/alan/anaconda3/envs/cuongpx/lib/python3.6/site-packages/setuptools/command/build_py.py", line 126, in build_package_data
        srcfile in self.distribution.convert_2to3_doctests):
    TypeError: argument of type 'NoneType' is not iterable
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/alan/anaconda3/envs/cuongpx/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6j6iaixz/suod/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6j6iaixz/suod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ms_fv72w/install-record.txt --single-version-externally-managed --compile --install-headers /home/alan/anaconda3/envs/cuongpx/include/python3.6m/suod Check the logs for full command output.`

**Comment by yzhao062** [comment]
I tried on my linux and mac--both installed fine. I am wondering if that is possible to update your pip and setuptools?

**Comment by SungmanHong** [comment]
Hi, I'm worker in a company. I'm using PyOD for outlier detection. I want to find the contamination percent, instead of setting the percentage. I found our data set has generally grouped one with standard deviation is 100 for inputs. I modified some in PyOD and now the my PCA algorithm with some threshold can find contamination percent automatically... However... it is not always working good...   Can i detect contamination percent automatically in PyOD or SUOD (or it can be updated??)
